apiVersion: v1
kind: Namespace
metadata:
  name: pgo-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pgo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tomtris02/go-app-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pgo-frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
