# Please edit the object below. Lines beginning with a '#' will be ignored,               
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#             
apiVersion: v1
kind: Service                                          
metadata:                                                                                                  
  annotations:                                                                                             
    kubectl.kubernetes.io/last-applied-configuration: |                                                    
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"cost-analyzer","app
  creationTimestamp: "2025-07-29T18:43:48Z"
  labels:                               
    app: cost-analyzer                   
    app.kubernetes.io/instance: kubecost 
    app.kubernetes.io/managed-by: Helm   
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-2.3.3
  name: kubecost-cost-analyzer             
  namespace: kubecost                      
  resourceVersion: "1713"                  
  uid: d6806fa1-2730-4f83-9eb4-9f6b27e091bd
spec:                     
  clusterIP: 10.43.196.151      
  clusterIPs:                   
  - 10.43.196.151               
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:                
  - IPv4                     
  ipFamilyPolicy: SingleStack
  ports:           
  - name: tcp-model
    nodePort: 31368 
    port: 9003        
    protocol: TCP     
    targetPort: 9003  
  - name: tcp-frontend
    nodePort: 30003 
    port: 9090      
    protocol: TCP     
    targetPort: 9090                    
  selector:                              
    app: cost-analyzer                   
    app.kubernetes.io/instance: kubecost 
    app.kubernetes.io/name: cost-analyzer
  sessionAffinity: None                  
  type: NodePort                         
status:                                  
  loadBalancer: {} 